name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          mkdir -p temp/amd64 temp/arm64
          GOOS=linux GOARCH=amd64 go build -o temp/amd64/main main.go
          GOOS=linux GOARCH=arm64 go build -o temp/arm64/main main.go

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: manifest/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/swcoffee/auditlimit:latest
            ghcr.io/swcoffee/auditlimit:${{ steps.date.outputs.date }}
